### ISSUE TITLE
Make "change" button's position static

### ISSUE THREAD

**Issue by MKLau** [CamFlow/cytoscape.js-prov#1]
I really like the options for different graph configurations. The type button moves around though, which makes it difficult to use.

**Comment by tfjmp** [comment]
Would you have a screenshot? The HTML of the example page is extremely basic (and bad), so I won't be a surprise if given any different resolution/browser combination it looked bad. I will look at it, if it becomes something we want to pursue.

**Comment by MKLau** [comment]
It’s hard to show it as a screenshot because the issue is that the button moves when you click on it. So, after you click it, if you want to change it again, you have to move the mouse to where the button moved to. Because of this, cycling through the different viewing options is clunky.

On Jul 14, 2016, at 2:45 PM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:

Would you have a screenshot? The HTML of the example page is extremely basic (and bad), so I won't be a surprise if given any different resolution/browser combination it looked bad. I will look at it, if it becomes something we want to pursue.

**Comment by tfjmp** [comment]
Fixed in 747ab3a11b5e3c8d373fbb5085e9e7ef262ffa33
