### ISSUE TITLE
"Inactive" nodes and edges are difficult to see

### ISSUE THREAD

**Issue by MKLau** [CamFlow/cytoscape.js-prov#3]
Maybe make them a little darker/brighter or if it's possible add a slidebar to adjust brightness

**Comment by tfjmp** [comment]
It is simply css modification. Right now the css is embedded in the JS for quick dev, but once more mature, you will be able to modify a lot of how the graph looks like (including changing the opacity of the faded nodes and edges).

**Comment by tfjmp** [comment]
Fixed in 06ed9dbf65b5183bb4cbe154edf6a5a2883bdc17
